services:
  - type: web
    name: gemad
    env: node
    region: frankfurt  # можешь поменять на us-east или другую, если хочешь
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 3000
